name: swd_mobile_app_test
description: "A Mobile App Test"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl:
  delightful_toast:
  get:
  flutter_svg:
  iconsax:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/png/
    - assets/images/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik Trials
      fonts:
        - asset: fonts/Aeonik Trials/AeonikTRIAL-Bold.otf
        - asset: fonts/Aeonik Trials/AeonikTRIAL-BoldItalic.otf
        - asset: fonts/Aeonik Trials/AeonikTRIAL-Light.otf
        - asset: fonts/Aeonik Trials/AeonikTRIAL-LightItalic.otf
        - asset: fonts/Aeonik Trials/AeonikTRIAL-Regular.otf
        - asset: fonts/Aeonik Trials/AeonikTRIAL-RegularItalic.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
